In [1]:
import sklearn  


In [3]:
import sklearn.datasets

iris = sklearn.datasets.load_iris()

iris_predictors = iris.data
iris_target = iris.target



In [7]:
import numpy as np

import pandas as pd

data = pd.DataFrame(iris_predictors, columns=iris.feature_names)
data['target'] = iris_target


In [8]:
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [10]:
data = data.sample(frac=1).reset_index(drop=True)  # Shuffle the data

In [11]:
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.4               3.4                1.5               0.4   
1                  6.0               2.7                5.1               1.6   
2                  5.0               3.5                1.3               0.3   
3                  5.6               2.5                3.9               1.1   
4                  6.7               2.5                5.8               1.8   
..                 ...               ...                ...               ...   
145                5.1               3.5                1.4               0.3   
146                6.0               2.2                4.0               1.0   
147                4.7               3.2                1.3               0.2   
148                6.2               3.4                5.4               2.3   
149                4.8               3.4                1.6               0.2   

     target  
0         0  
1         1  
2         0  
3         1  
4         2  
..      ...  
145       0  
146       1  
147       0  
148       2  
149       0  

[150 rows x 5 columns]

In [12]:
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.4               3.4                1.5               0.4   
1                6.0               2.7                5.1               1.6   
2                5.0               3.5                1.3               0.3   
3                5.6               2.5                3.9               1.1   
4                6.7               2.5                5.8               1.8   

   target  
0       0  
1       1  
2       0  
3       1  
4       2

In [14]:
data.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [15]:
data["petal length (cm)"]= data["petal length (cm)"].astype(float)
data["petal width (cm)"]= data["petal width (cm)"].astype(float)
data["sepal length (cm)"]= data["sepal length (cm)"].astype(float)
data["sepal width (cm)"]= data["sepal width (cm)"].astype(float)
data["target"]= data["target"].astype(int)


In [116]:
x=data.drop("target",axis=1)
y=data["target"]

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=46)
train_data = pd.concat([x_train, y_train], axis=1)
train_data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
97                 7.1               3.0                5.9               2.1   
124                6.3               2.5                4.9               1.5   
19                 5.1               3.4                1.5               0.2   
119                6.1               3.0                4.6               1.4   
121                6.3               3.3                6.0               2.5   
..                 ...               ...                ...               ...   
93                 6.4               2.7                5.3               1.9   
146                6.0               2.2                4.0               1.0   
116                6.3               2.7                4.9               1.8   
40                 4.6               3.4                1.4               0.3   
69                 5.6               2.8                4.9               2.0   

     target  
97        2  
124       1  
19        0  
119       1  
121       2  
..      ...  
93        2  
146       1  
116       2  
40        0  
69        2  

[120 rows x 5 columns]

In [ ]:
class NaiveBayes:
    def __init__(self, data,target_column='target'):
        self.data = data
        self.target_column = target_column
        self.classes = np.unique(data[self.target_column])
        self.class_priors = {}
        self.feature_means = {}
        self.feature_vars = {}  

    def fit(self):
        for cls in self.classes:
            cls_data = self.data[self.data[self.target_column] == cls]
            self.class_priors[cls] = len(cls_data) / len(self.data)
            self.feature_means[cls] = cls_data.drop(columns=self.target_column).mean()
            self.feature_vars[cls] = cls_data.drop(columns=self.target_column).var()
        print("Data fitted successfully.")
    
    def predict(self, X):
        predictions = []
        for _, row in X.iterrows():
            class_probs = {}
            for cls in self.classes:
                prior = self.class_priors[cls]
                likelihood = np.prod(
                    (1 / np.sqrt(2 * np.pi * self.feature_vars[cls])) *
                    np.exp(-((row - self.feature_means[cls]) ** 2) /
                           (2 * self.feature_vars[cls])))

                class_probs[cls] = prior * likelihood
            predictions.append(max(class_probs, key=class_probs.get))
        return predictions
    def accuracy(self, X, y):
        predictions = self.predict(X)
        return np.mean(predictions == y)
    

In [118]:
classifier = NaiveBayes(train_data)
classifier.fit()

Data fitted successfully.


In [119]:
y_pred = classifier.predict(x_test)


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)#actual -> predicted -downward

Confusion Matrix:
[[ 9  0  0]
 [ 0 12  0]
 [ 0  1  8]]


In [121]:
from sklearn.metrics import  classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.92      1.00      0.96        12
           2       1.00      0.89      0.94         9

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30



In [122]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train, y_train)
y_pred_gnb = gnb.predict(x_test)
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred_gnb)
print(accuracy)

0.9666666666666667


In [143]:
data2=pd.read_csv("Diabetes.csv")

In [144]:
data2

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [125]:
data2.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [145]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [146]:
y =pd.DataFrame(data2['Outcome'])
data2= data2.drop(columns=['Outcome'])
data2_mean = data2.mean()
data2_std = data2.std() 
data2= (data2 - data2_mean) / data2_std  

x_train, x_test, y_train, y_test = train_test_split(data2, y, test_size=0.2, random_state=42)

In [147]:
train_data2 = pd.concat([x_train,y_train], axis=1)

In [148]:
class2= NaiveBayes(train_data2, target_column='Outcome')
class2.fit()

Data fitted successfully.


In [149]:
y_pred = class2.predict(x_test)

In [156]:
y_test=np.array(y_test).flatten()

In [163]:
len(y_pred)

154

In [164]:
len(y_test)


154

In [166]:
accuracy_score(y_test, y_pred)

0.7662337662337663

c:\Users\Shresth\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Shresth\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Shresth\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(avera

In [133]:
y

'              precision    recall  f1-score   support\n\n           0       0.30      1.00      0.46         9\n           1       0.00      0.00      0.00        12\n           2       0.00      0.00      0.00         9\n\n    accuracy                           0.30        30\n   macro avg       0.10      0.33      0.15        30\nweighted avg       0.09      0.30      0.14        30\n'

In [167]:
confusion_matrix(y_test, y_pred)

array([[79, 20],
       [16, 39]], dtype=int64)

In [168]:
gb= GaussianNB()
gb.fit(x_train, y_train)
y_pred_gb = gb.predict(x_test)
accuracy_gb = accuracy_score(y_test, y_pred_gb)

c:\Users\Shresth\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [169]:
accuracy_gb

0.7662337662337663

In [141]:
y_pred_gb

array([2, 2, 0, 0, 2, 0, 2, 2, 1, 1, 1, 0, 2, 1, 0, 1, 1, 1, 1, 0, 0, 2,
       1, 0, 1, 1, 2, 0, 1, 1])